// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrbhxvphlmqdjinyuqep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyYmh4dnBobG1xZGppbnl1cWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDYwNTAsImV4cCI6MjA2Nzk4MjA1MH0.7I9cXadRTOme2UzXQeOEt4lAG5gO0FM3f-5eO0GYBsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});