// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdqbkbcxshzifltzpdop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkcWJrYmN4c2h6aWZsdHpwZG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODUyMzgsImV4cCI6MjA2OTM2MTIzOH0.CLuTMwYG18Clrx89ZYzhhv8erO-jAoJypr5A9YPLVwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});